import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <nav>
          <Link href="/" style={{opacity:1, fontSize:'1rem', letterSpacing:'-0.01em', textTransform:'none', fontFamily:'Playfair Display, serif'}}>
            Bookstore
          </Link>
          <div style={{display:'flex', gap:'2rem'}}>
            <Link href="/authors">Autores</Link>
            <Link href="/crear">Crear autor</Link>
            <Link href="/books">Libros</Link>
            <Link href="/books/crear">Crear libro</Link>
            <Link href="/favoritos">Favoritos</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}